### PR TITLE
Avoid persistance

### PR DESCRIPTION
**Pull request by Oizaro**

### CODE REVIEW

**Comment by Oizaro** [comment]
@tvinzz

A little help... Could you try this script on a phone or emulator? Strangely don't work on my phone but only on a script extension of Chrome.

Maybe there's some syntax errors somewhere. I dontknow honestly...

Thanks in advance.

**Comment by tvinzz** [comment]
the `avoidPersistance` is a good idea, but it has the problem described here https://github.com/AdguardTeam/DisableAMP/issues/10#issuecomment-630106212.

**Comment by ameshkov** [comment]
There's more to that. If you want to use that approach and automatically redirect AMP pages to their respective non-AMP versions, you need edit `meta.template.js` and change (or add more) `@include` tags there

**Comment by Oizaro** [comment]
@tvinzz @ameshkov

I have found a solution to the problem described on https://github.com/AdguardTeam/DisableAMP/issues/10#issuecomment-630106212:

In practice just fill the attribute 'href' with 'data-amp-cur' content, and the contextual menù to open new tab will read the standard webpage link.

**Comment by Oizaro** [comment]
New PR for you:

https://github.com/AdguardTeam/DisableAMP/pull/19

**Pull request merged**
