### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by Oizaro**
Wrong reference

### CODE REVIEW

**Comment by Oizaro** [comment]
@tvinzz

This is my last PR. I did a series of tests on my phone, and nothing abnormal has occurred on usual sites with amp that I visit.

Regards...

**Comment by Oizaro** [comment]
@tvinzz @ameshkov

This is my last PR. I did a series of tests on my phone, and nothing abnormal has occurred (except the fix inside this PR obviously) on sites with amp that I usually visit.

Regards...

**Comment by ameshkov** [comment]
Thank you!

We'll get it from here and see if there are any other cases that aren't yet covered.

**Comment by Oizaro** [comment]
@ameshkov

If you need a test build I have posted a link here: https://github.com/AdguardTeam/DisableAMP/issues/10

**Pull request merged**
